# Generated by Django 5.2.5 on 2025-08-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_writing', 'in writing'), ('pending_editor_approval', 'pending editor approval'), ('published', 'published')], default='in_writing', max_length=32)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
